export default {
  ADD_LIST: 'ADD_LIST',
  REMOVE_LIST: 'REMOVE_LIST',
  EDIT_TITLE_LIST: 'EDIT_TITLE_LIST',

  ADD_CARD: 'ADD_CARD',
  REMOVE_CARD: 'REMOVE_CARD',
  EDIT_TITLE_CARD: 'EDIT_TITLE_CARD',
};
